### DISCUSSION TITLE
使用github的workflow定期完成

### DISCUSSION THREAD

**Discussion by Cnlomou** [ygxiuming/QN-big-study#8] [Ideas]
### 1、fork代码并填写名单.xls（不会可以参照README.md)
[教程](https://github.com/ygxiuming/QN-big-study#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)
### 2、设置定时时间
修改文件QN-big-study/blob/main/.github/workflows/docker-image.yml
``` yml
on:
   schedule:
    - cron: "20 13 * * 3"  #这里是每周3晚上9点多
```  
[怎么设置时间](https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#schedule)
### 3、将代码传上自己的仓库
每周会自动完成
